### ISSUE TITLE
Java compiler

### ISSUE THREAD

**Issue by clblalock** [ngmarchant/dblink#1]
We're limited to the software that our IT will allow. We are trying to get IntelliJ IDEA installed as indicated in the guide.  

Can we bypass this issue by using the prebuilt JAR file, which the guide says is recommended? If so, can you fix the link in the guide? It looks like the link is a placeholder that hasn't been filed in.

**Comment by ngmarchant** [comment]
Depending on the version of Spark you're running, you may need to build the JAR yourself.

Thanks for noticing the broken link. It should now point to the releases page where you can download a JAR built against Spark v2.3.1.
