### ISSUE TITLE
Data from d-blink paper

### ISSUE THREAD

**Issue by vikmary** [ngmarchant/dblink#10]
Hi,
Thanks for your paper!
I'm looking for datasets for the task of Entity Resolution. Can you share the preprocessed data used in "d-blink: Distributed End-to-End Bayesian Entity Resolution"? 
Best regards,
Mariia

**Comment by resteorts** [comment]
These should be coming very soon on the cleanzr repository! We're working very hard to organize the datasets that work directly with the paper. We hope that these will be posted in the next couple of weeks as we're working on code that will work with the data sets and the dblink repository as well as a README file that will be informative. :)

**Comment by vikmary** [comment]
That was a quick response, thank you!
Looking forward to the upcoming commits

**Comment by resteorts** [comment]
Sure thing!
