### ISSUE TITLE
Development environment

### ISSUE THREAD

**Issue by YathishK** [ngmarchant/dblink#13]
Hi , 

Is it possible to share your development environment information in the documentation? What kind of Spark cluster you are using , is it on AWS or individual standalone cluster?  Are you using Elipse or Intellij Idea software or any other software for IDE? Is Scala IDE or Scala IDE plugin is used?

These are more of questions to understand the application better than an issue. 
Thank you,
Yathish

**Comment by resteorts** [comment]
AWS. The IntelliJ IDEA Community edition. Yes, it's written in Scala.
