### ISSUE TITLE
10K sample runs

### ISSUE THREAD

**Issue by YathishK** [ngmarchant/dblink#5]
dblink application ran good on RLdata10000.csv with samplesize of 100 and 1000. Sample size of 1000 produced the same results as in published paper for  RLdata10000.csv . 

Ran dblink application with 10K sample on data files (RLdata10000.csv, EDMSimulationv2.mac.csv) , both ran for long time (more than 6 hours) and failed. Attached here spark-submit log files (after removing IP address and server names). Also attached config file used to run the application. 

After certain stages , the application is running on few cores even though spark-submit provided 345 cores (attached below a sample screenshot) 

[ABSEmployee_log.txt](https://github.com/cleanzr/dblink/files/3647301/ABSEmployee_log.txt)
[RLdata10000_log.txt](https://github.com/cleanzr/dblink/files/3647303/RLdata10000_log.txt)
[ABSEmployee_64partitions_PCG-I.txt.conf.txt](https://github.com/cleanzr/dblink/files/3647310/ABSEmployee_64partitions_PCG-I.txt.conf.txt)
[RLdata10000.conf.txt](https://github.com/cleanzr/dblink/files/3647311/RLdata10000.conf.txt)
![Capture](https://user-images.githubusercontent.com/53016370/65513967-5ac24b00-deaa-11e9-81ff-6b68868ab0f7.JPG)

**Comment by ngmarchant** [comment]
From the log file:
>19/09/23 15:18:39 WARN SparkContext: Spark is not running in local mode, therefore the checkpoint directory must not be on the local filesystem. Directory '/tmp/spark_checkpoint/' appears to be on the local filesystem.

This indicates you're running Spark in cluster mode. In cluster mode, all paths should point to locations on HDFS storage. In other words, the outputPath and checkpointPath variables should be URIs like `hdfs://path/to/directory/`. 

Currently, you're using locations on the local filesystem, which may not be accessible to all executors/the driver. I suspect this may be the cause of the issues (a checkpoint from a previous state of the chain is needed, but can't be accessed).

**Comment by resteorts** [comment]
You're getting a warning message here that suggests that you do not have the paths set up correctly, so I would double and triple check that this is correct. Please have multiple people look into this as perhaps it may not be set up correctly? Otherwise, we do not think it would throw a warning.

**Comment by YathishK** [comment]
We are running Spark in client mode. All paths are pointed to HDFS storage, The warning is misleading , the folder _/tmp/spark_checkpoint/_ is created on HDFS. I see intermediate RDDs in that folder on HDFS.
Local Linux file names are entirely different than HDFS file names.  just would like to clarify that local Linux  file system does not have **_examples_** folder , it is only available on HDFS.

Did you ever run dblink application with samplesize of 10000 ? What is the command you used ? What is your cluster size ?

**Comment by ngmarchant** [comment]
Please continue this discussion on reproducibility in Issue #4
