### ISSUE TITLE
Controlling log 

### ISSUE THREAD

**Issue by YathishK** [ngmarchant/dblink#7]
log4j.properties controls the log generated in Spark driver and worker nodes. 
can we change  
_log4j.rootCategory=INFO, console, file_ 
to 
_log4j.rootCategory=WARN, console_ 
in log4j.properties file

**Comment by resteorts** [comment]
Why are you wishing to change this?

**Comment by YathishK** [comment]
The application with sample size of 10K run creating huge log on driver and worker nodes. Often times the browser is not responding, so by limiting the log messages to warning and errors, it would be easy to navigate.

**Comment by resteorts** [comment]
@YathishK Could you clarify what you mean by browser? Are you not running things from the command line? Perhaps I'm not fully understanding your meaning. I would not recommend opening log files in a browser. But again, I may not understand your question.

**Comment by ngmarchant** [comment]
> log4j.properties controls the log generated in Spark driver and worker nodes.
> can we change
> _log4j.rootCategory=INFO, console, file_
> to
> _log4j.rootCategory=WARN, console_
> in log4j.properties file

Yes, you can set up the logging however you like. I think we were using that configuration for debugging purposes.

**Comment by YathishK** [comment]
![image](https://user-images.githubusercontent.com/53016370/66134061-b33dca80-e5c5-11e9-8aed-c2d9cb53bfd6.png)

stderr will take us to the log file. 

Thank you
