### ISSUE TITLE
Source code and Jar file 

### ISSUE THREAD

**Issue by YathishK** [ngmarchant/dblink#8]
Hello , 

Looks like the jar file is not generated from the same Source code on Git. The jar file is creating additional step in output run file. Source code project.scala does not have this step.

Scheduled steps
---------------
  * SampleStep: Evolving the chain from new initial state with sampleSize=100, burninInterval=0, thinningInterval=10 and sampler=PCG-I
  * SummarizeStep: Calculating summary quantities {'cluster-size-distribution', 'partition-sizes'} along the chain for iterations >= 0
  * EvaluateStep: Evaluating sMPC clusters (computed from the chain for iterations >= 100) using {'pairwise', 'cluster'} metrics

**Comment by charlesa101** [comment]
i noticed this as well

**Comment by ngmarchant** [comment]
That part of the output is not generated in `Project.scala`. It's generated [here](https://github.com/cleanzr/dblink/blob/d32d7d442f4095b80a53564ca221263c50a32364/src/main/scala/com/github/cleanzr/dblink/ProjectSteps.scala#L38).

**Comment by YathishK** [comment]
Thank you for clarification
